version: '3.8'

services:
  web:
    build:
      context: .   # Diretório atual
      dockerfile: Dockerfile  # Dockerfile especificado
    ports:
      - "7010:80"  # Mapeamento de porta
    volumes:
      - .:/var/www/html  # Mapeia o diretório atual para o contêiner
    networks:
      - atende  # Conecta à rede externa 'atende'
    environment:
      DB_HOST: 172.20.0.6     # IP do contêiner MySQL na rede atende
      DB_USER: root           # Usuário do banco de dados
      DB_PASSWORD: Ncm@647534 # Senha do banco de dados
      DB_NAME: candelaria     # Nome do banco de dados
    restart: always  # Reinicia o contêiner automaticamente em caso de falha

networks:
  atende:
    external: true  # Usa a rede Docker externa 'atende'
